CREATE TABLE IF NOT EXISTS invoices (
  id BIGINT NOT NULL AUTO_INCREMENT,
  invoice_type VARCHAR(64) NULL,
  invoice_code VARCHAR(64) NULL,
  invoice_number VARCHAR(64) NULL,
  invoice_date DATE NULL,
  check_code VARCHAR(128) NULL,
  machine_code VARCHAR(128) NULL,
  invoice_status VARCHAR(32) NOT NULL DEFAULT 'Pending',
  is_red_invoice TINYINT(1) NOT NULL DEFAULT 0,
  red_invoice_ref VARCHAR(128) NULL,
  seller_name VARCHAR(255) NULL,
  seller_tax_id VARCHAR(64) NULL,
  seller_address VARCHAR(255) NULL,
  seller_phone VARCHAR(64) NULL,
  seller_bank VARCHAR(255) NULL,
  seller_bank_account VARCHAR(128) NULL,
  buyer_name VARCHAR(255) NULL,
  buyer_tax_id VARCHAR(64) NULL,
  buyer_address VARCHAR(255) NULL,
  buyer_phone VARCHAR(64) NULL,
  buyer_bank VARCHAR(255) NULL,
  buyer_bank_account VARCHAR(128) NULL,
  total_amount_without_tax DECIMAL(18, 2) NULL,
  total_tax_amount DECIMAL(18, 2) NULL,
  total_amount_with_tax DECIMAL(18, 2) NULL,
  amount_in_words VARCHAR(255) NULL,
  drawer VARCHAR(128) NULL,
  reviewer VARCHAR(128) NULL,
  payee VARCHAR(128) NULL,
  remarks TEXT NULL,
  purchase_order_no VARCHAR(64) NULL,
  source_file_path VARCHAR(512) NULL,
  raw_ocr_json JSON NULL,
  llm_json JSON NULL,
  schema_version VARCHAR(32) NOT NULL DEFAULT 'v1',
  expected_amount DECIMAL(18, 2) NULL,
  amount_diff DECIMAL(18, 2) NULL,
  risk_flag TINYINT(1) NOT NULL DEFAULT 0,
  risk_reason JSON NULL,
  handler_user VARCHAR(64) NULL,
  handler_reason TEXT NULL,
  handled_at DATETIME NULL,
  leader_user VARCHAR(64) NULL,
  notify_personal_status VARCHAR(32) NOT NULL DEFAULT 'NotSent',
  notify_personal_msg_id VARCHAR(128) NULL,
  notify_leader_status VARCHAR(32) NOT NULL DEFAULT 'NotSent',
  notify_leader_msg_id VARCHAR(128) NULL,
  unique_hash CHAR(64) NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_invoices_unique_hash (unique_hash),
  KEY idx_invoices_invoice_code_number (invoice_code, invoice_number),
  KEY idx_invoices_invoice_date (invoice_date),
  KEY idx_invoices_risk_flag (risk_flag),
  KEY idx_invoices_purchase_order_no (purchase_order_no)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
